# -*- coding: utf-8 -*-
"""For_Looping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WplUEZ8IxTmu1GyTKLzk97MHWlXHA-rD
"""

for i in range(10,0,-1):
  print(i)

for i in range(2,22,2):
  print(i)

for i in range(5,55,5):
  print(i)

for i in range(2,20,2):
  print(i)

for i in range(1,23,2):
  print(i)

for i in range(1,7):
  print(i**2)

for i in range(1,7):
  print(i**3)

for i in range(1,7):
  print((i**3)+1)

for i in range(1,7):
  print((i**2)-1)

n=int(input())
sum=0
for i in range(1,n+1):
  sum+=i
print(sum)

# Check sum of even or odd numbers 
sume,sumo,n=0,0,int(input())
for i in range(1,n+1):
  if i%2==0:
    sume+=i
  else:
    sumo+=i
print("Sum of even numbers={} and Sum of odd numners ={}".format(sume,sumo))

# For looping in string
str=input()
for ch in str:
  print(ch)

str=input()
for ch in range(0,len(str)):
  print(str[ch])

for i in range(1,5):
  for j in range(1,6):
    print(i,j,sep="\t")

# Print pattern
for i in range(1,6):
  for j in range(5,0,-1):
    print(j,end=" ")
  print()

# Print pattern
for i in range(1,6):
  for j in range(1,6):
    print(i,end=" ")
  print()

# Print pattern
for i in range(5,0,-1):
  for j in range(1,6):
    print(i,end=" ")
  print()

# Pattern 
for i in range(5,0,-1):
  for j in range(i,0,-1):
    print(i,end=" ")
  print()

# Pattern 
n=5
for i in range(1,6):
  for j in range(i,0,-1):
    print(n,end=" ")
  n=n-1
  print()

# Pattern 
for i in range(1,6):
  for j in range(i,0,-1):
    print(j,end=" ")
  print()

# Pattern 
for i in range(1,6):
  for j in range(i,i-1):
    print(i,end=" ")
  print()



# Pattern 
for i in range(5,0,-1):
  for j in range(i,0,-1):
    print(j,end=" ")
  print()

