# -*- coding: utf-8 -*-
"""Python_Course_Scratch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S3SW1qngXumJeGguijXOTlQbWCdgGM6b
"""



"""Difference btw C and Python 
* Its procedural 
* Shorter code 
* No inialisation 
* Dynamic Memory 
* Compatible with other interfaces 



"""

# Conversion into Decimal Number System 
n=0O123
print(int(n))
n=0B101010
print(int(n))
n=0XAF43
print(int(n))

# Convert into binary | decimal | hexadecimal 
n=100
print(bin(n))
print(hex(n))

"""DAY2- Printing statements in Python """

# Adding and multiplication of two numbers 
a=int(input("Enter the number"))
b=int(input("Enter the number"))
s=a+b
m=a*b
# Printing in the same line 
print("The sum of two numbers is",s,"The multiplication of two numbers is=",m)
# Printing in different line 
print("The sum=",s,"\n","The multiplication=",m)

"""Separators
*   sep=" "
*   In the same line, the by default = space
*   Can modify acc to ur need 

End
*    end= " " 
*    Affects the next line to be printed.
*    If end="\n", statement in the next line by default 


"""

print("Hello", "Everyone")
print("Hello", "Everyone", sep=",")
print("Hello","Everyone",sep="\t", end=" * ")
print("My name is ananya")

"""Assignment Opertaors"""

# Power of a number 
print("5 to the power 4 is written as",5**4)
# Unpacking of the values in the single line 
a,b,c=10,20,30
print("a=",a,"b=",b,"c=",c)
# Unpacking taking the input values as well
x,y,z=input(),input(),input()
print(x,y,z)

"""Operators in Python

*   Arithmetic: +,-,*,/,//,%,**
*   Assignmnet: =,+=,-=, .....
*   Relational: >,<,==,!=,<=,>=
*   Logical: and , or , not 
*   Boolean: True , False 
*   Bitwise: &,|,^,<<,>>,~
*   Unary Minus
*   Membership and Identity 


"""

# ARITHEMETIC
a,b=30,15
print("Decimal Divison", a/b)
print("Integer Divison", a//b)
print("Remainder Divison", a%b)

# UNARY MINUS 
a=30
b=-a
c=-b
print(a,b,c)

# RELATIONAL OPERATORS 
a,b=10,20
print(a>b , a<=b , a>=b, a==b , a!=b, sep="\t",end=" ^ ")
# CHAINED RELATIONAL OPERATORS 
x=15
print(10<x<20)
print(1<2>3<4)

# LOGICAL OPERATORS 
# AND : returns the second value 
# OR  : returns the first value 
# Or - 1st statement , if no condition otherwise true or false 
x=500
y=200
# or hence will give 500 
print(x or y)
print( not x)

x,y,z=1,2,3
if x<y and y<2:
  print('yes')
else:
  print('no')
if x<y or y<2:
  print('yes')
else:
  print('no')

# BOOLEAN OPERATORS 
# AND : Both true then true 
# OR : One true then true 
a,b=True, False 
print(a and b, a or b , not a , not b , a and a , b or b , b and b)

# BITWISE OPERATORS 
# Converting a number into binary format
n=45
print("Binary of",n,"=",bin(n))

# BITWISE AND (&)
x=10
y=11
print(x,y)
print)

x=0b00001010
y=0b00001011
c=x&y
print(c)

# Calculate the area and perimenter of a rectangle 
l,b=int(input()),int(input())
area,peri=l*b, 2*(l+b)
print("The area=%f The perimeter=%f" %(area,peri))

# Sum mul subs div point quoteint remainder  % term
a,b=int(input()),int(input())
sum,mult,subs,div,fdiv,rem=a+b,a*b,a-b,a//b,a/b,a%b
print("Sum=%f\nMultiplication=%i\nSubstraction=%i\nDivision=%i\nDecimal_Divison=%f\nRemainder=%i " %(sum,mult,subs,div,fdiv,rem))

print("helo","there",sep="-")

# FORMAT STRING 
a=10
b=20
print("sum ={}\nmultiplication={}".format(a+b,a*b))

# Inputting values together 
a,b,c = [int(x) for x in input("Enter the number").split('+')]
print(a,b,c)

a =eval(input("enter number"))
print(a)

"""CALCULATE THE SUM OF DIGITS OF A NUMBER """

num=int(input("Enter a  number"))
sum=0
while num!=0:
  rem=num%10
  sum+=rem
  num=num//10
print("The sum of digits of a number={}".format(sum))

num=476
sum=0
rem=num%10
sum+=rem
num=num//10
rem=num%10
sum+=rem
num=num//10
rem=num%10
sum+=rem
num//=10
print("Sum of digits=",sum)

# REVERSE OF A NUMBER 
rev=0
num=476
rem=num%10
rev=rev*10+rem
num=num//10
rem=num%10
rev=rev*10+rem
num=num//10
rem=num%10
rev=rev*10+rem
num//=10
print("Sum of digits=",rev)

"""IF ELSE CONDITIONS
 IF 
1. Used for more than two conditions 
2. Checks all the statements 

IF ELSE 
1. Used for two conditions 
2. faster as condition based
            
"""

# Check the angles of a triangle and check if it is valid or not 
a,b,c = [int(x) for x in input("Enter the angles").split()]
sum=a+b+c
if sum==180:
  print("The triangle is valid, as the sum=%i" %sum)
else:
  print("The triangle is invalid as the sum of angles=%i" %sum)

# Doing with only if
a,b,c = [int(x) for x in input("Enter the angles").split()]
sum=a+b+c
if sum==180:
  print("The trainagle is valid")
if sum!=180:
  print("The triangle is inavlid ")

# Enter a number and check whether it s positive negative or zero 
a=int(input("Enter the number"))
if a>0:
  print("The number %i is a positive number" %a )
if a<0:
  print("The number %i is a negative number" %a )
if a==0:
  print("The number %i is a zero" %a )

# CALCULATE PROFIT OR LOSS
sp,cp = [int(x) for x in input("Enter the number").split()]
if sp>cp:
  profit=sp-cp
  print("The profit=%i" %profit)
else:
  loss=cp-sp
  print("The loss =%i" %loss)
print("***************************************************************")
sp,cp = [int(x) for x in input("Enter the number").split()]
if sp>cp:
  profit=sp-cp
  print("The profit=%i" %profit)
if cp>sp:
  loss=cp-sp
  print("The loss =%i" %loss)

# Check whether a number is even or odd 
a=int(input("Enter a number"))
if a%2==0:
  print("%i is an even number"%a)
else:
  print("%i is an odd number"%a)

print("*******************************************************")
a=int(input("Enter a number"))
if a%2==0:
  print("%i is an even number"%a)
if a%2!=0:
  print("%i is an odd number"%a)

# Enter the bill amount and calcuate the discount rate 
bill=int(input("Enter the bill amount"))
if bill>50000:
  d=0.05
  bill-=bill*d
  print("The bill=%i"%bill)
else:
  d=0.02
  bill-=bill*d
  print("The bill=%i"%bill)

# Check whether an year is a leap year or not 
YR=int(input("Enter the year"))
if YR%4==0:
  print("The year is leap year")
else:
  print("The year is not a leap year")

# Conversion of distance into kilometers 
d=float(input("Enter the distance in meter"))
print("The distance in kms=%f"% (d*0.001))

# Enter the age group of a person and check whether a person can vote or not 
age=int(input("Enter the age grp of a person "))
if age>=18:
  print("A person can vote")
else:
  print("A person cannot vote")

print("*****************************************************")
if age>18:
  print("A person can vote")
if age<18:
  print("A person cannot vote")
if age==18:
  print("A person can vote")

"""NESTED ELSE IF """

# ENTER THE COORDINATES OF A GRAPH AND CHCK WHETHER THEY LIE ON X, Y PLANE OR X OR BY AXIS OR THE ORIGIN 
x,y=[int(x) for x in input("Enter the coordinates").split()]
if x==0:
  if y==0:
    print("Coordinates {} lie at the Origin".format(x,y))
  else:
     print("Coordinates {} lie at the Y-axis".format(x,y))
else:
   if y==0:
    print("Coordinates {} lie at the X-axis".format(x,y))
   else:
     print("Coordinates {} lie at the XY-plane".format(x,y))

# Doing the same questions using elif ladder 
x,y=[int(x) for x in input("Enter the coordinates").split()]
if x==0:
  if y==0:
    print("Origin")
  else:
    print("Y axis")
elif y==0:
  if x!=0:
    print("X axis")
  else:

x,y=[int(x) for x in input("Enter the coordinates").split()]
if x==0:
  if y==0:
    print("origin")
  else:
    print("Y axis")
elif y==0:
  print("X axis")
else:
  print("XY plane")

# Enter three number and check the greatest of the three number
a,b,c=[int(x) for x in input("Enter the coordinates").split()]
if a>b:
  if a>c:
    print("a is greater")
  else:
    print("c is greAter")
elif b>c:
  print("b is greater")
else:
  print("c is greater")

# Do the coordinate question using elif ladder and logical operators 
x,y=[int(x) for x in input().split()]
if x==0 and y==0:
  print("Origin")
elif x==0 and y!=0:
  print("Y axis")
elif y==0 and x!=0:
  print("X axis")
else:
  print("XY plane ")

# CHECK FOR THE LEAP YEAR 
x=int(input())
if ((x%100==0 and x%400==0) or (x%4==0 and x%100!=0)):
  print("Leap year")
else:
  print("INVALID")

# enter three sides of a triangle and chcek whetherthe triangle is an equilateral triangle or an isoceles triangle or a acsnle triagle 
a,b,c=[int(x) for x in input().split()]
if a==b and a==c and b==c:
  print("Equilateral triangle")
elif a==b or b==c or a==c:
  print("Isoceles triangle")
else:
  print("Scalene triangle")

# enter 3 sides of a triangle, and check whether te tri is valid or not 
# Note: the triangle is valid only if the sum of any two sides is always greater than the thord side of the triabgle 
a,b,c=[int(x) for x in input().split()]
s_ab=a+b
s_bc=b+c
s_ca=c+a
if s_ab>c or s_bc>a or s_ca>b:
  print("Valid")
else:
  print("Invalid")

#Enter three sides of a triangle and check whether the tiangle is a right angle trianhle or not 

a,b,c=[int(x) for x in input().split()]
if (a**2+b**2 == c**2) or  (b**2+c**2== a**2) or (a**2+c**2== b**2):
  print("Its a right angle")
else:
  print("Not a right angle ")

"""LOOPING using while loop """

n=10
while n>=1:
  print(n,end=" ")
  n-=1

n=2
while n<=20:
  print(n,end=" ")
  n+=2

n=5
while n<=50:
  print(n,end=" ")
  n+=5

n=1
while n<=21:
  print(n,end=" ")
  n+=2

n=1
while n<=6:
  print(n**2,end=" ")
  n+=1

n=1
while n<=6:
  print(n**3,end=" ")
  n+=1

# Series: 2 9 28 65 126 217
n=1
while n<=6:
  print(n**3+1,end=" ")
  n+=1

# Series: 0 3 8 15 24 15::::::::::: 0+3=3 8-3=5 15-8=7 , 3,5,7
n=3
s=0
while n<=11:
  s+=n
  print(s,end=" ")
  n+=2

# REVERSE OF A NUMBER
rev=0
n=int(input("Enter a number"))
nn=n
while(n!=0):
  rem=n%10
  rev=rev*10+rem
  n//=10
print("The reverse of {} are {}".format(nn,rev))

# ENTER A NUMBER AND CHECK THE NUMBER OF DIGITS IN A NUMBER
count=0
n=int(input("Enter a number"))
nn=n
while(n!=0):
  count+=1
  n//=10
print("The number of digits in {} are {}".format(nn,count))

# SPY NUMBER OR NOT
sum=0
mult=1
n=int(input("Enter a number"))
nn=n
while(n!=0):
  rem=n%10
  sum+=rem
  mult*=rem
  n//=10
if sum==mult:
  print("{} is a spy number".format(nn))
else:
  print("{} is not a spy number".format(nn))

n=int(input("Enter a number"))
sum=0
sq=n**2
while sq!=0:
  rem=sq%10
  sum+=rem
  sq//=10
if sum==n:
  print("Its a good number")
else:
  print("Its not a good number")

# FACTORIAL OF A NUMBER 
n=int(input("Entera  number"))
prod=1
while(n>=1):
  prod*=n
  n-=1
print("The factorial of the number is", prod)

# PRINT THE MULTIPLIICATION TABLE 
n=7
i=1
while(i<=10):
  print("{} * {} = {}".format(n,i,n*i))
  i+=1

# cook your dish here
T=int(input())
for i in range(T):
    X,Y=[int(x) for x in input().split()]
    if X+Y >6:
        print("YES")
    else:
        print("NO")

# Enter a number and check whether its prime or not 
num=int(input("Enter a number"))
i=2
while i<=num//2:
  if num%i==0:
    print("Its not a prime numer ")
    break
  i+=1
if i>num//2:
  print("Its a prime numer")

# Calculate the prime factors of a number entered by the user
n=int(input("Enter the number whose prime factors are to be calculated"))
i=2
while n!=1:
  if n%i==0:
    print(i,end=" ")
    n=n//i
    continue
  i+=1

n=int(input("Enter the number whose prime factors are to be calculated"))
i=2
while n!=1:
  if n%i==0:
    print(i,end=" ")
    n=n//i
  else:
    i+=1

"""# FOR LOOPS : DESIGN THIS CODE 
    1
    2 1 
    3 2 1
    4 3 2 1 
    5 4 3 2 1 
"""

for i in range(1,6,1):
  for j in range(i,0,-1):
    print(j,end="")
  print()

for i in range(5,0,-1):
  for j in range(5,i-1,-1):
    print(j,end="")
  print()

for i in range(1,11,2):
  for j in range(1,i+1,2):
    print(j,end=" ")
  print()

for i in range(9,0,-2):
  for j in range(i,9+1,2):
    print(j,end="")
  print()

for i in range(5,0,-1):
  for j in range(i,6):
    print(i,end=" ")
  print()

n=1
for i in range(1,6):
  for j in range(1,i+1):
    print(n,end=" ")
  n=n+2
  print()

for i in range(1,11,2):
  for j in range(i,11,2):
    print(i,end=" ")
  print()

for i in range(1,15,2):
  for j in range(9,i-1,-1):
    print(j,end=" ")
  print()

for i in range(1,11,2):
  for j in range(i,9+1):
    print(j,end=" ")
  print()

